server.port=8090
#Connection to database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/abarrotes
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver